Apps
digitalocean/openapi pull request #460
Opened 2020-12-15 14:21 UTC by ChiefMateStarbuck

fixes #245
fixes #249
fixes #416
fixes #417
fixes #239
fixes #247
fixes #250
fixes #248
fixes #241
fixes #242
fixes #244
fixes #240

2020-12-15 14:24 UTC, ChiefMateStarbuck commented
!deploy

2020-12-18 17:36 UTC, scotchneat commented
!deploy

2020-12-18 18:41 UTC, scotchneat requested changes
This is a big change so I'm still going through it. So far it looks good with respect to it being a proper spec and rendering right in the preview. 

My first request would be to check how the files for other resources are formatted and apply the same approach in these files for consistency. Admittedly, these are nitpicking as none of these affect the spec functionally but are more for us and for consistency.
* Add sane white space between top-level keys per file
* Order the top-level keys in a file 

I've included some example changes.

I also noticed there are some extension properties (`x-originalParamName`) that look like they were added by the `kin-openapi` library during the conversion from v2 to v3 spec. I don't think we need to keep those.

2020-12-18 18:41 UTC, scotchneat commented on specification/resources/apps/delete_app.yml
> +- Apps
```suggestion
operationId: delete_app

summary: Delete an App

description: Delete an existing app. Once deleted, all active deployments will be
  permanently shut down and the app deleted. If needed, be sure to back up your app
  specification so that you may re-create it at a later time.

parameters:
  - $ref: parameters.yml#/id_app

tags:
- Apps

responses:
  "200":
    $ref: responses/delete_app.yml
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
```

2020-12-18 18:41 UTC, scotchneat commented on specification/resources/apps/create_app.yml
> +- Apps
```suggestion
operationId: create_app

summary: Create a New App

description: Create a new app by submitting an app specification. For documentation
  on app specifications (`AppSpec` objects), please refer to [the product documentation](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/).

tags:
- Apps

requestBody:
  content:
    application/json:
      schema:
        $ref: models/apps_create_app_request.yml
  required: true
  x-originalParamName: body

responses:
  "200":
    $ref: responses/new_app.yml
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
```

2020-12-18 18:41 UTC, scotchneat commented on specification/resources/apps/create_app.yml
> +  x-originalParamName: body
This looks like it came from `kin-openapi` during generation. I don't think we need to keep this.

2020-12-18 19:12 UTC, ChiefMateStarbuck commented on specification/resources/apps/delete_app.yml
> +- Apps
Yes! I remember this conversation now. I'll work on this.

2021-01-07 23:42 UTC, andrewsomething commented on specification/resources/apps/models/apps_deployment_progress_step.yml
> +      $ref: apps_deployment_progress_step.yml
```suggestion
      # FIXME: Circular refs are not currently supported by Prism
      # https://github.com/stoplightio/prism/issues/1456
      # $ref: apps_deployment_progress_step.yml
      type: object
```

Breaking Prism will halt contract testing work. I don't love this, but it might be the best thing to do for now to unblock this.  @digitalocean/api-cli any thoughts?

2021-01-08 15:32 UTC, ChiefMateStarbuck commented on specification/resources/apps/models/apps_deployment_progress_step.yml
> +      $ref: apps_deployment_progress_step.yml
Committed 👍

2021-01-08 15:39 UTC, ChiefMateStarbuck commented on specification/resources/apps/models/apps_deployment_progress_step.yml
> +      $ref: apps_deployment_progress_step.yml
this has broken the linter. Will fix soon.

2021-01-13 18:13 UTC, scotchneat approved these changes
Per the team discussion:
We did find discrepancies with at least one response model and example which would require quite a bit of refactoring. Given this is such a large change, and the spec is still in beta, we decided to go ahead and merge this change and work on resolving the discrepancies in smaller PRs.

Since there are fixes to the circular references which affected prism validation, then this is good to go.

2021-01-14 01:40 UTC, merged