apps request/response clean up
digitalocean/openapi pull request #480
Opened 2021-02-11 16:19 UTC by ChiefMateStarbuck

2021-02-11 20:19 UTC, andrewsomething requested changes

2021-02-11 20:19 UTC, andrewsomething commented on specification/resources/apps/models/app_component_base.yml
> -  gitlab:
It's not clear to me why these are being removed here as well the fields in other files.  The are valid parts of the App Specification.

https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/
https://pkg.go.dev/github.com/digitalocean/godo#AppSpec

I think the models are fine as is. I think the create app operation could use a example for the request body. Without a specific example, the default examples for each possible field get used. 

https://github.com/digitalocean/openapi/blob/main/specification/resources/apps/create_app.yml#L15

2021-02-16 17:49 UTC, scotchneat approved these changes
Looks good

2021-02-16 18:10 UTC, andrewsomething approved these changes
Looks great!

I did have one question in-line, but not necessarily blocking. Just want to understand it.

2021-02-16 18:10 UTC, andrewsomething commented on docker-compose.yaml
> +      - "8090:4010"
Why the change here?

2021-02-16 18:24 UTC, ChiefMateStarbuck commented on docker-compose.yaml
> +      - "8090:4010"
I found that running both a spec preview and a prod mock at the same time can help with visibility into any code changes. since both the preview and the prod mock both ran on port 8080, changing this port helps allows for both to be run simultaneously.

2021-02-16 18:24 UTC, merged

2021-02-16 18:32 UTC, andrewsomething commented on docker-compose.yaml
> +      - "8090:4010"
:+1: