Use environment variables for tokens in Go and Ruby examples.
digitalocean/openapi pull request #493
Opened 2021-03-17 20:13 UTC by andrewsomething

Let's recommend good practices and make these consistent with the cURL examples.

2021-03-17 21:29 UTC, dbrian57 approved these changes
lgtm! Thanks for cleaning this up.

2021-03-19 19:37 UTC, scotchneat approved these changes
This looks good. 
What do you think about changing `pat` to `token` in the go examples to be consistent across languages?

2021-03-19 19:51 UTC, andrewsomething commented
@scotchneat  Good idea. Updated.

2021-03-19 19:59 UTC, scotchneat requested changes
Oops. Looks like some extra lines were matched.

2021-03-19 19:59 UTC, scotchneat commented on specification/resources/certificates/examples/go/create_certificates.yml
> +      key, err := ioutil.ReadFile("/tokenh/to/privkey1.pem")
You could try matching `pat :=` and `(pat)` instead.

2021-03-19 20:00 UTC, andrewsomething commented on specification/resources/certificates/examples/go/create_certificates.yml
> +      key, err := ioutil.ReadFile("/tokenh/to/privkey1.pem")
:facepalm:

2021-03-19 20:48 UTC, scotchneat approved these changes
:shipit:

2021-03-19 21:28 UTC, merged