Ported Original API Intro Text to API Description
digitalocean/openapi pull request #508
Opened 2021-04-19 18:03 UTC by dbrian57

Ported the [intro text from Developers](https://developers.digitalocean.com/documentation/v2/#introduction) into the spec's initial description field. Not a fan of the excessive whitespace, but I think we can fix that in the CSS on the docs site.

Thoughts welcome!

2021-04-19 18:15 UTC, andrewsomething commented
!deploy

2021-04-19 19:24 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +  description: |
I wonder if this is something that can be ref-ed from another file?

```
  description:
    $ref: 'introduction.yaml'
```

2021-04-19 19:30 UTC, scotchneat commented on specification/DigitalOcean-public.v2.yaml
> +  description: |
Agreed. Rebilly takes that approach and it works well - https://github.com/Rebilly/api-definitions/blob/master/openapi/combined.yaml#L17.
They even take it further in their [despription.md](https://github.com/Rebilly/api-definitions/blob/master/openapi/description.md) and reference common errors nicely

2021-04-19 19:37 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +  description: |
Nice! I didn't actually realize you could ref a markdown file directly. That would make it much easier to edit on its own.

2021-04-19 19:51 UTC, dbrian57 commented on specification/DigitalOcean-public.v2.yaml
> +  description: |
That's a really good idea! I'll report back the results.

2021-04-20 20:59 UTC, scotchneat commented
Well, bummer. Sorry to lead you down that path @dbrian57 
It seems the Rebilly implementation just uses the Redoc tooling (openapi-cli) and don't leverage spectral like us. Redoc is running some custom spec parsing beyond what the actual OpenAPI v3 specification supports to enable this.

We might have to revisit using external markdowns some other time.

2021-04-28 22:20 UTC, andrewsomething commented
!deploy

2021-04-29 14:08 UTC, andrewsomething commented
!deploy

2021-04-29 14:25 UTC, andrewsomething commented on specification/description.yml
> +  export TOKEN=your_token_here
```suggestion
  export DIGITALOCEAN_TOKEN=your_token_here
```

2021-04-29 14:25 UTC, andrewsomething commented on specification/description.yml
> +  curl -X $HTTP_METHOD -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/$OBJECT"
```suggestion
  curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"
```

2021-04-29 14:25 UTC, andrewsomething commented on specification/description.yml
> +  ## OAuth Authentication
This is just an idea and doesn't need to block this. Redoc creates a section for "Authentication" using the `securitySchemes`. That mostly empty section has felt a bit awkward to me.

https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/redoc-index.html?pr=508#section/Authentication

Wonder if we could rework the content here so that it shows up under the Redoc "Authentication" header.

https://github.com/digitalocean/openapi/blob/059a164acebf788fb555304a3b0f98fba3d2c05b/specification/DigitalOcean-public.v2.yaml#L1184-L1187

Looks like it can contain a `description` https://swagger.io/specification/#security-scheme-object

2021-04-29 16:49 UTC, dbrian57 commented on specification/description.yml
> +  ## OAuth Authentication
all for this and agree. Let me see what I can do

2021-05-10 20:52 UTC, andrewsomething commented
!deploy

2021-05-10 21:17 UTC, andrewsomething requested changes

2021-05-10 21:17 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +        #### Authenticate with a Bearer Authorization Header
Redoc's docs mention `<PullRight>` which would move this to the right hand example column, but it looks like this is only part of their hosted version: 

https://redoc.ly/docs/api-reference-docs/embedded-markdown/#pull-right
https://redoc.ly/redoc-vs-reference/

2021-05-10 21:17 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +        curl -X $HTTP_METHOD -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/$OBJECT"
```suggestion
        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"
```

Let's use `DIGITALOCEAN_TOKEN` to be consistent with the examples.

2021-05-10 21:17 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +            curl -H "Authorization: Bearer $TOKEN" \
```suggestion
            curl -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
```

2021-05-10 21:17 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +             curl -H "Authorization: Bearer $TOKEN" \
```suggestion
             curl -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
```

2021-05-10 21:17 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +        ### Parameters
Looks like this isn't a sub-topic of authentication in the current docs. It's it's own section:

https://developers.digitalocean.com/documentation/v2/#parameters

2021-05-10 21:17 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +        ### Cross Origin Resource Sharing
Same here:

https://developers.digitalocean.com/documentation/v2/#cors

2021-05-11 15:55 UTC, scotchneat approved these changes
This is great @dbrian57! 

One question (not blocking because this is how it is in the current docs too): 
We describe how to use OAuth tokens for authentication but it's not specifically stated that one can use an API token as well. Do you know if that's intentionally left out?

2021-05-11 17:32 UTC, dbrian57 commented
> I think it's just being a bit imprecise with the language and is using Oauth tokens and personal access tokens interchangeably.

@andrewsomething @scotchneat That's exactly the case and all of this could use a little tightening up, but I think that's outside the scope of this PR.

As for the requested changes, I've broken out each sub-section to mirror the sections on Developers. Thoughts?

2021-05-11 19:30 UTC, scotchneat commented
!deploy

2021-05-11 19:33 UTC, scotchneat submitted a review, later dismissed
LGTM!

2021-05-13 14:47 UTC, dbrian57 commented on specification/DigitalOcean-public.v2.yaml
> +        #### Authenticate with a Bearer Authorization Header
Yeah, I tried the pull-right format and it didn't work. 🤷

2021-05-18 18:10 UTC, andrewsomething approved these changes

2021-05-18 18:11 UTC, merged