WIP: Add monitoring endpoints to spec
digitalocean/openapi pull request #528
Opened 2021-05-11 17:29 UTC by mdanzinger

WIP - do not merge.

This PR adds the new monitoring endpoints to the openapi spec.

2021-05-11 17:29 UTC, mdanzinger commented
!deploy

2021-05-11 18:54 UTC, andrewsomething commented
!deploy

2021-05-11 19:13 UTC, mdanzinger commented
!deploy

2021-05-11 19:29 UTC, mdanzinger commented
!deploy

2021-07-28 18:06 UTC, mdanzinger commented
!deploy

2021-07-28 18:38 UTC, ChiefMateStarbuck commented on specification/DigitalOcean-public.v2.yaml
> +
```suggestion
```

2021-07-28 18:38 UTC, ChiefMateStarbuck commented on specification/DigitalOcean-public.v2.yaml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck requested changes
Great work! I'm suggesting some removal of empty lines.

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/resources/monitoring/list_alerts.yml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/DigitalOcean-public.v2.yaml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/DigitalOcean-public.v2.yaml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/resources/monitoring/list_alerts.yml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/resources/monitoring/models/slack_details.yml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/resources/monitoring/parameters.yml
> +
```suggestion
```

2021-07-28 18:43 UTC, ChiefMateStarbuck commented on specification/resources/monitoring/responses/alert_policy_response.yml
> +
```suggestion
```

2021-07-29 14:50 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +    description: >-
We should probably mention that these are in beta here.

2021-07-29 14:50 UTC, andrewsomething commented on specification/resources/monitoring/create_alert.yml
> +summary: Create Alert Policy
```suggestion
summary: "[Beta] Create Alert Policy"
```

Might not be a bad idea to prefix these with `[Beta]`. This is the first major beta API since we moved to the new API documentation platform so we don't have a pattern yet. Though this is similar to how the old custom site worked. Adding `product_lifecycle: beta` to an operation there would prefix the operation's title with `Beta`.

2021-07-29 14:53 UTC, ChiefMateStarbuck submitted a review, later dismissed

2021-08-06 15:48 UTC, mdanzinger commented on specification/DigitalOcean-public.v2.yaml
> +    description: >-
Hey @andrewsomething, the API has been in a closed beta, the plan is for it to be GA at the time of merging this.

2021-08-06 15:50 UTC, mdanzinger commented on specification/resources/monitoring/create_alert.yml
> +summary: Create Alert Policy
Good catch - should have done this initially as the generated preview docs were used as the beta docs. The API is entering GA with the merge of this PR, so I don't think this is necessary anymore.

2021-08-06 16:08 UTC, ChiefMateStarbuck commented
!deploy

2021-08-06 16:09 UTC, ChiefMateStarbuck approved these changes

2021-08-06 16:09 UTC, merged