CURL Examples for Monitoring Service
digitalocean/openapi pull request #563
Opened 2021-11-04 19:53 UTC by dbrian57

What is says on the tin! I verified each example using my account. Note: the JSON payloads for the POST and PUT requests require single quotes instead of double quotes, i.e. that formatting was intentional. Thanks, API team!

2021-11-04 22:56 UTC, scotchneat requested changes
Thanks, @dbrian57! I added some suggestions and questions inline.

2021-11-04 22:56 UTC, scotchneat commented on specification/resources/monitoring/examples/curl/create_alert.yml
> +    --data '<JSON-payload>'
Unless the value for the `--data` arg was intentionally left as `<JSON-payload>`, I'd prefer to include a working example where possible. Something like:

```suggestion
    --data '{"alerts":{"email":["alerts@example.com"],"compare":"GreaterThan","description":"CPU Alert","enabled":true,"entities":["12345678"],"tags":["droplet_tag"],"type":"v1/insights/droplet/cpu","value":80,"window":"5m"}'
```

2021-11-04 22:56 UTC, scotchneat commented on specification/resources/monitoring/examples/curl/create_alert.yml
> +    "https://api.digitalocean.com/v2/monitoring/alerts"
This is missing the backslash after the URL value

```suggestion
    "https://api.digitalocean.com/v2/monitoring/alerts" \
```

2021-11-04 22:56 UTC, scotchneat commented on specification/resources/monitoring/examples/curl/update_alert.yml
> +    "https://api.digitalocean.com/v2/monitoring/alerts/78b3da62-27e5-49ba-ac70-5db0b5935c64"
This also needs a backslash after the URL. 

```suggestion
    "https://api.digitalocean.com/v2/monitoring/alerts/78b3da62-27e5-49ba-ac70-5db0b5935c64" \
```

2021-11-04 22:56 UTC, scotchneat commented on specification/resources/monitoring/examples/curl/update_alert.yml
> +    --data '<JSON-payload>'
Same question/suggestion here for the `<JSON-payload>`

```suggestion
    --data ''{"alerts":{"email":["alerts@exmaple.com"],"slack":[{"channel":"Production Alerts","url":"https://hooks.slack.com/services/T1234567/AAAAAAAA/ZZZZZZ"}]},"compare":"GreaterThan","description":"CPU Alert","enabled":true,"entities":["12345678"],"tags":["droplet_tag"],"type":"v1/insights/droplet/cpu","value":80,"window":"5m"}''
```

2021-11-05 17:06 UTC, dbrian57 commented
@scotchneat Thanks Cesar!

2021-11-05 18:53 UTC, scotchneat approved these changes
Awesome. LGMT 👍🏽

2021-11-05 18:54 UTC, merged