Add database/config GET and database/config Patch
digitalocean/openapi pull request #564
Opened 2021-11-08 22:24 UTC by ebergstromDO

This PR adds the database config commands to the database part of the API. I would appreciate a fairly in depth review as I'm unsure of it.

2021-12-02 17:08 UTC, ChiefMateStarbuck requested changes
Very good work. Thank you. Although an approval from another DATABASE team member is not necessary, it is certainly helpful.

2021-12-02 17:08 UTC, ChiefMateStarbuck commented on specification/resources/databases/get_database_config.yml
> +  Note: Database config is not yet supported for Redis and Postgres clusters.
```suggestion
  **Note:** Database config is not yet supported for Redis and Postgres clusters.
```

It looks like the word `NOTE:` is bolded in the rest of the Database files.

2021-12-02 17:08 UTC, ChiefMateStarbuck commented on specification/resources/databases/patch_database_config.yml
> +  Note: Database configuration is not supported for Redis and Postgres clusters.
```suggestion
  **Note:** Database configuration is not supported for Redis and Postgres clusters.
```

2021-12-02 17:19 UTC, rpmoore approved these changes

2022-03-04 18:38 UTC, bentranter commented
Closing in favour of #590

2022-03-04 18:38 UTC, closed without merging