Database config
digitalocean/openapi pull request #571
Opened 2021-12-02 18:40 UTC by rpmoore

2021-12-02 19:44 UTC, bentranter requested changes
A few small tweaks, but looking good overall!

2021-12-02 19:44 UTC, bentranter commented on specification/resources/databases/responses/databases_copy.yml
> +description: A JSON object with a key of `databases`.
This file appears to be identical to [github.com/digitalocean/openapi/specification/resources/databases/responses/databases.yml](https://github.com/digitalocean/openapi/blob/3d352a60aa4404069eaf777619a157b74aa9b5b1/specification/resources/databases/responses/databases.yml), could we remove this one? It doesn't seem like the new endpoint references this response, so it might've been mistakenly added in the PR you picked up on.

2021-12-02 19:44 UTC, bentranter commented on specification/resources/databases/examples/curl/get_database_config.yml
> +  curl -X POST \
Should this be `GET` instead of `POST`?

2021-12-02 19:44 UTC, bentranter commented on specification/resources/databases/patch_database_config.yml
> +          - type: object
I believe that the `allOf` statement is unnecessary here, since you can use the reference directly:
```suggestion
  content:
    application/json:
      schema:
        $ref: ''models/database_config.yml''
```

2021-12-03 13:41 UTC, ChiefMateStarbuck commented
!deploy

2021-12-03 18:24 UTC, rpmoore commented on specification/resources/databases/examples/curl/get_database_config.yml
> +  curl -X POST \
Good catching, fixing!

2021-12-03 18:29 UTC, rpmoore commented on specification/resources/databases/responses/databases_copy.yml
> +description: A JSON object with a key of `databases`.
yeah, they are identical. Not sure why it was added and I can't find any references to it. I'll go ahead and remove it.

2021-12-03 23:13 UTC, rpmoore commented on specification/resources/databases/patch_database_config.yml
> +          - type: object
I think this is meant to be `oneOf`, I know the plan for this API call is for it to accept different payloads depending on the engine type. I do think that the `- type: object` needs to be removed though.

2021-12-09 21:03 UTC, bentranter commented
Looking at this again, I see that the response for `PATCH` isn't showing up as expected (see https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/redoc-index.html?pr=571#operation/patch_database_config).

@rpmoore, do you want me to take over this PR from here? I know it can be quite a bit of work to iterate on this given our tooling (and the pain of writing a ton of YAML 😛) – I'd be happy to take this over and then tag you for a final review of the generated docs to confirm that it's as expected.

2022-03-04 18:38 UTC, bentranter commented
Closing in favour of #590

2022-03-04 18:38 UTC, closed without merging