create namespace API
digitalocean/openapi pull request #582
Opened 2022-02-04 05:15 UTC by v-shant

This is a Draft PR, just to make sure I am adding APIs in the correct format and in the right way, still open for review but we can merge once all the CRUD operations will be added.

2022-02-04 20:49 UTC, andrewsomething requested changes

2022-02-04 20:49 UTC, andrewsomething commented on specification/resources/serverless/responses/namespace_created.yml
> +content:
You can use the shared ratelimit-limit components here:

```suggestion
headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
```

2022-02-04 20:49 UTC, andrewsomething commented on specification/resources/serverless/models/namespace_info.yml
> +    example: null
This is causing a linting error as the example's type isn't a string. If `null` is a valid response, than you can add `nullable: true` If not, just add a random string to use as an example.

2022-02-04 20:57 UTC, andrewsomething commented
!deploy

2022-02-04 22:22 UTC, piyush0101 commented on specification/DigitalOcean-public.v2.yaml
> +    description: Provides methods for CRUD operations for namespaces.
nit: should this say "Provides methods for CRUD operations for function namespaces"

2022-02-14 17:34 UTC, scotchneat commented
!delpoy

2022-02-16 15:52 UTC, ChiefMateStarbuck commented
!deploy

2022-02-22 15:57 UTC, andrewsomething commented
Converting this to a draft for now to make sure it is not inadvertently merged following our conversation last week.

2022-09-07 14:08 UTC, closed without merging