DBAAS-2875: Update public API with the missing config options
digitalocean/openapi pull request #608
Opened 2022-04-12 20:34 UTC by shabtaisharon

2022-04-12 20:35 UTC, ChiefMateStarbuck commented
!deploy

2022-04-12 20:51 UTC, shabtaisharon commented
Hi @ChiefMateStarbuck,
Can you please help me understand why the PR validation failed?

2022-04-12 21:04 UTC, yGabriel reviewed
Left some in-line edits!

2022-04-12 21:04 UTC, yGabriel commented on specification/resources/databases/models/mysql.yml
> +      to false also truncates the mysql.slow_log table. Default is off
```suggestion
      When enabled, captures slow queries. When disabled, also
      truncates the mysql.slow_log table. Default is false.
```

2022-04-12 21:04 UTC, yGabriel commented on specification/resources/databases/models/mysql.yml
> +      long_query_time seconds to execute. Default is 10s
```suggestion
      The time, in seconds, for a query to take to execute before 
      being captured by slow_query_logs. Default is 10 seconds.
```

2022-04-13 14:41 UTC, ChiefMateStarbuck requested changes

2022-04-13 14:41 UTC, ChiefMateStarbuck commented on specification/resources/databases/models/mysql.yml
> +      - 'null'
```suggestion
```
`type` should only be `- string`

2022-04-13 17:07 UTC, shabtaisharon commented on specification/resources/databases/models/mysql.yml
> +      - 'null'
Thank you!

2022-04-13 18:10 UTC, ChiefMateStarbuck approved these changes

2022-04-13 18:10 UTC, merged