UDP support for load balancers
digitalocean/openapi pull request #610
Opened 2022-04-15 18:43 UTC by dbrian57

This PR adds UDP support to the list of available protocols for load balancers.

2022-04-15 21:38 UTC, ChiefMateStarbuck commented
!deploy

2022-04-25 15:05 UTC, andrewsomething requested changes

2022-04-25 15:05 UTC, andrewsomething commented on specification/resources/load_balancers/models/forwarding_rule.yml
>      example: https
```suggestion
    - udp
    example: https
```

Looks like `udp` is missing from the enum list for `entry_protocol`

2022-06-24 19:06 UTC, ChiefMateStarbuck approved these changes

2022-06-27 13:49 UTC, andrewsomething approved these changes
:+1:  lgtm!

2022-06-27 13:49 UTC, merged