registry: Update operationId for new pattern.
digitalocean/openapi pull request #641
Opened 2022-05-09 22:17 UTC by andrewsomething

Updates the `operationId` for the new `{resource}_{action}` pattern. It retains the use of `registry` (singular) in order to be consistent with the path (`/v2/registry`).

2022-05-10 21:21 UTC, ChiefMateStarbuck submitted a review, later dismissed
Thank you for helping out @andrewsomething

2022-05-10 21:21 UTC, ChiefMateStarbuck commented on specification/DigitalOcean-public.v2.yaml
> +      $ref: 'resources/registry/registry_get_docker_credentials.yml'
`registry_get_dockerCredentials`

endpoint_action_everythingElseInCamel

This applies to a few endpoints

2022-05-10 21:54 UTC, andrewsomething commented on specification/DigitalOcean-public.v2.yaml
> +      $ref: 'resources/registry/registry_get_docker_credentials.yml'
Is that what we're doing elsewhere?  Feels a bit odd to me to mix camel case and snake case this way. 

For grouping, autorest requires the resource to be the first fragment before the first underscore (`{resource}_{action}`). Is it opinionated about what comes after that? How does it effect the generated client?

2022-05-11 06:21 UTC, danaelhe commented on specification/DigitalOcean-public.v2.yaml
> +      $ref: 'resources/registry/registry_get_docker_credentials.yml'
Yeah, it is weird but autorest can get funny with multiple underscores *sometimes*. I think it was with volume_actions where it would drop some words from the generated python functions signatures after the second underscore. So we tried to keep it to just one underscore. So with volumeActions_create_byName you'll see that autorest created a function that's "create_by_name", so that confirms they understood how to handle the camel case for byName. 

I did just run autorest with these changes and it seems like autorest did create a "build_get_docker_credentials_request". So in this case, it seems fine. Maybe it's when the resource has an underscore that trips autorest up.

2022-05-11 06:24 UTC, danaelhe requested changes
The operationID in `specification/resources/registry/registry_list_repository_manifests.yml ` needs to be updated: registry_list_repository_manifests

2022-05-12 01:08 UTC, danaelhe approved these changes
lgtm, thanks!

2022-05-12 18:52 UTC, merged