APPS-5636 App Platform updates
digitalocean/openapi pull request #656
Opened 2022-05-18 23:04 UTC by ElanHasson

* Add Functions Alert rule types
* Spelling and grammar fixes
* Update minimumTLSVersion to only support 1.2 and 1.3

2022-05-18 23:13 UTC, kamaln7 approved these changes

2022-05-18 23:13 UTC, kamaln7 commented on specification/resources/apps/models/app_domain_spec.yml
> +  minimumTLSVersion:
```suggestion
  minimum_tls_version:
```

2022-05-18 23:27 UTC, rcj4747 approved these changes

2022-05-19 02:34 UTC, rcj4747 submitted a review, later dismissed

2022-05-20 22:17 UTC, andrewsomething requested changes
Looks good, but one small change requested inline.

2022-05-20 22:17 UTC, andrewsomething commented on specification/resources/apps/models/app_domain_spec.yml
> +    format: string
```suggestion
```

We've actually recently removed all other instances of  `format: string` from this as some OpenAPI tooling didn't understand how to handle it. Technically it should be fine as the spec describes `format` as an open string-valued property, but since `string` as a format is redundant with the type, we took the simple path of removing it.  

https://swagger.io/specification/#data-types

2022-05-20 22:26 UTC, andrewsomething approved these changes

2022-05-20 22:39 UTC, merged