Add documentation for new dbaas api
digitalocean/openapi pull request #659
Opened 2022-05-23 20:40 UTC by shabtaisharon

2022-05-23 20:49 UTC, ChiefMateStarbuck commented
!deploy

2022-05-24 17:17 UTC, ChiefMateStarbuck requested changes
Failing lint

2022-05-24 17:33 UTC, ChiefMateStarbuck commented on specification/resources/databases/models/pgbouncer.yml
> +    example: '0'
```suggestion
    example: 0
```

`'0'` is a string. removing the commas will make it an integer. There are a few places in this file you'll need to update this.

2022-05-24 20:54 UTC, ChiefMateStarbuck commented on specification/resources/databases/models/pgbouncer.yml
> +    example: 0
```suggestion
    example: 1
```

`0` is not a valid example. This is an odd bug with openAPI

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/mysql.yml
> +      is only started if previous backup has already completed.
```suggestion
      The hour of day (in UTC) when backup for the service starts. New backup
      only starts if previous backup has already completed.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/mysql.yml
> +      only started if previous backup has already completed.
```suggestion
      The minute of the backup hour when backup for the service starts. New backup 
      only starts if previous backup has already completed.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/postgres.yml
> +      is only started if previous backup has already completed.
```suggestion
      The hour of day (in UTC) when backup for the service starts. New backup
     only starts if previous backup has already completed.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/postgres.yml
> +      only started if previous backup has already completed.
```suggestion
      The minute of the backup hour when backup for the service starts. New backup is
      only started if previous backup has already completed.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      seconds, they are freed. If 0 then timeout is disabled. [seconds]
```suggestion
      If the automatically-created database pools have been unused this many
      seconds, they are freed. If 0, timeout is disabled.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      (regardless of user). Setting it to 0 means unlimited.
```suggestion
      Only allows a maximum this many server connections per database
      (regardless of user). If 0, allows unlimited connections.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      a pool doesn't exist.
```suggestion
      If non-zero, automatically creates a pool of that size per user when
      a pool doesn't exist.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      be dropped. If 0 then timeout is disabled. [seconds]
```suggestion
      Drops server connections if they have been idle more than this many seconds. 
      If 0, timeout is disabled. 
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      connected longer than this. [seconds]
```suggestion
      The pooler closes any unused server connection that has been
      connected longer than this amount of seconds.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      inactivity. The value is effectively capped at the pool size.
```suggestion
      If current server connections are below this number, adds more. Improves
      behavior when usual load comes suddenly back after period of total
      inactivity. The value is effectively capped at the pool size.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +      description: Enum of parameters to ignore when given in startup packet
```suggestion
      description: Enum of parameters to ignore when given in startup packet.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +    description: List of parameters to ignore when given in startup packet
```suggestion
    description: List of parameters to ignore when given in startup packet.
```

2022-05-24 20:55 UTC, yGabriel commented on specification/resources/databases/models/pgbouncer.yml
> +    description: Run server_reset_query (DISCARD ALL) in all pooling modes
```suggestion
    description: Run server_reset_query (DISCARD ALL) in all pooling modes.
```

2022-05-24 22:27 UTC, ChiefMateStarbuck approved these changes

2022-05-24 22:27 UTC, merged