Fix Monitoring Alert Policy Response and Curl Examples
digitalocean/openapi pull request #707
Opened 2022-08-02 20:48 UTC by danaelhe

Uncovered a few API/documentation mismatches when writing the tests for the python client.

The current documentated CURL request example doesn't seem to work:
```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
  "https://api.digitalocean.com/v2/monitoring/alerts" \
  --data '{"alerts":{"email":["alerts@example.com"],"compare":"GreaterThan","description":"CPU Alert","enabled":true,"entities":["12345678"],"tags":["droplet_tag"],"type":"v1/insights/droplet/cpu","value":80,"window":"5m"}' 

{"id":"bad_request","message":"failed to decode body into request: unexpected EOF","request_id":"c4f4dc0f-9fa9-40b0-8198-4caaa622ec87"}
```

had to change it to this:
```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
  "https://api.digitalocean.com/v2/monitoring/alerts" \
  --data '{"alerts":{"email":["alerts@example.com"]},"compare":"GreaterThan","description":"CPU Alert","enabled":true,"entities":["310953751"],"tags":["droplet_tag"],"type":"v1/insights/droplet/cpu","value":80,"window":"5m"}'

{"policy":{"uuid":"0202e21a-7bb8-4d7b-8198-15b958e87605","type":"v1/insights/droplet/cpu","description":"CPU Alert","compare":"GreaterThan","value":80,"window":"5m","entities":["310953751"],"tags":["droplet_tag"],"alerts":{"slack":[],"email":["alerts@example.com"]},"enabled":true}}
```

Also, the documentation writes that the create and update response looks like this:
```
{
  "alerts": {
    "email": [
      "bob@exmaple.com"
    ],
    "slack": [
      {
        "channel": "Production Alerts",
        "url": "https://hooks.slack.com/services/T1234567/AAAAAAAA/ZZZZZZ"
      }
    ]
  },
  "compare": "GreaterThan",
  "description": "CPU Alert",
  "enabled": true,
  "entities": [
    "192018292"
  ],
  "tags": [
    "droplet_tag"
  ],
  "type": "v1/insights/droplet/cpu",
  "uuid": "78b3da62-27e5-49ba-ac70-5db0b5935c64",
  "value": 80,
  "window": "5m"
}
```

when really it looks like this:
```
{
  "policy": {
    "uuid": "0202e21a-7bb8-4d7b-8198-15b958e87605",
    "type": "v1/insights/droplet/cpu",
    "description": "CPU Alert",
    "compare": "GreaterThan",
    "value": 80,
    "window": "5m",
    "entities": [
      "310953751"
    ],
    "tags": [
      "droplet_tag"
    ],
    "alerts": {
      "slack": [],
      "email": [
        "alerts@example.com"
      ]
    },
    "enabled": true
  }
}
```

2022-08-02 20:49 UTC, ChiefMateStarbuck approved these changes
!deploy

2022-08-02 20:50 UTC, ChiefMateStarbuck requested changes
Linter 🏠

2022-08-04 15:22 UTC, andrewsomething approved these changes
:+1:  LGTM!

2022-08-04 15:28 UTC, ChiefMateStarbuck approved these changes

2022-08-04 15:28 UTC, merged