serverless Namespaces public APIs
digitalocean/openapi pull request #715
Opened 2022-09-07 14:09 UTC by v-shant

[RFC](https://docs.google.com/document/d/1WZW6admF1QpAJIag9E0lnLoxQFxWlyUEMX0D5qWxuE8/edit#)

2022-09-07 19:31 UTC, bentranter requested changes
Hey @v-shant, a few high level pieces of feedback:

* The operation ID names need some changes. We use the operation IDs to generate code, so they need to be very consistent. The pattern is roughly `<namespace>_<crud-operation>`, so for example, `create_namespace` should instead be `namespaces_create`. This allows us to generate code like `client.namespaces.create()`.
* The filenames should match the operation IDs for consistency. For example, `get_namespace.yml` should be `namespaces_get.yml`.

If you could fix those, I'll go over this PR in more detail. We'll also need to wait for someone from the product docs team to go over this as well before merging (hence the label that was added).

2022-09-08 16:11 UTC, andrewsomething commented
> The operation ID names need some changes. We use the operation IDs to generate code, so they need to be very consistent. The pattern is roughly <namespace>_<crud-operation>, so for example, create_namespace should instead be namespaces_create. This allows us to generate code like client.namespaces.create().

Do we want `namespaces` to be the top level here with methods to look like `client.namespaces.create()`? I think `serverless` or `functions` would be the better option. So the operation ID `serverless_create_namespace` in that case, generating `client.serverless.create_namespace()`

2022-09-08 16:27 UTC, piyush0101 commented on specification/DigitalOcean-public.v2.yaml
> +  - name: Serverless
this should be `Functions`?

2022-09-08 16:40 UTC, v-shant commented
> > The operation ID names need some changes. We use the operation IDs to generate code, so they need to be very consistent. The pattern is roughly _, so for example, create_namespace should instead be namespaces_create. This allows us to generate code like client.namespaces.create().
> 
> Do we want `namespaces` to be the top level here with methods that look like `client.namespaces.create()`? I think `serverless` or `functions` would be the better option. So the operation ID would be `serverless_create_namespace` in that case, generating `client.serverless.create_namespace()`

can't use functions_create_namespace as its warning me 

```
operationid-must-follow-new-naming-conventions  POST /v2/functions/sandbox - functions_get_sandbox should end with one of: create, post, add, tag, install, reset, upgrade, recycle, run, retry, validate, assign, unassign, cancel, destroy, delete, update, attach, revert, commit. Prefer 'create' for new resources. Custom verbs may be acceptable for clarity. Example OperationID: droplet_create
```

2022-09-08 16:54 UTC, bentranter commented
> Do we want `namespaces` to be the top level here with methods that look like `client.namespaces.create()`? I think `serverless` or `functions` would be the better option. So the operation ID would be `serverless_create_namespace` in that case, generating `client.serverless.create_namespace()`

Yeah good call, I wasn't thinking about the design of this at a high enough level.

From Piyush's comment, it seems like `functions` may be the best name (looks like that change is already being made).

I also wonder about the create sandbox endpoint. It seems like this is a find-or-create type of endpoint. @andrewsomething do you have any thoughts about how something like this should be named? Maybe just find_or_create like you see in ORMs?

2022-09-08 20:09 UTC, piyush0101 commented
> > Do we want `namespaces` to be the top level here with methods that look like `client.namespaces.create()`? I think `serverless` or `functions` would be the better option. So the operation ID would be `serverless_create_namespace` in that case, generating `client.serverless.create_namespace()`
> 
> Yeah good call, I wasn't thinking about the design of this at a high enough level.
> 
> From Piyush's comment, it seems like `functions` may be the best name (looks like that change is already being made).
> 
> I also wonder about the create sandbox endpoint. It seems like this is a find-or-create type of endpoint. @andrewsomething do you have any thoughts about how something like this should be named? Maybe just find_or_create like you see in ORMs?

I discussed with Vishant, we'll be removing the `sandbox` endpoint from the spec. It powers the now-deprecated sandbox functionality via `doctl`. This endpoint is not intended for use by the end users, we'll eventually remove it.

2022-09-08 20:10 UTC, dbrian57 requested changes
This is looking good. The documentation updates are inline. 

I still don't have a clear understanding of the `api-host` field, so that will need to be cleared up to. I tried to be thorough about the line formatting/indentation but it might need another pass after the feedback has been implemented.

Let me know if you have any questions. I'd like to do one more pass after this round. Thanks, Vishant!

2022-09-08 20:10 UTC, dbrian57 commented on specification/resources/serverless/sandbox_get.yml
> +  Creates or Gets existing sandbox namespace for the given uuid.
Per the conversation in Slack, we're not documenting this call, right?

2022-09-08 20:10 UTC, dbrian57 commented on specification/resources/serverless/responses/list_namespaces.yml
> +description: The response will be an array of JSON objects with a key called `namespaces`.
```suggestion
description: |- 
  An array of JSON objects with a key called `namespaces`.  Each object represents a namespace and contains
  the properties associated with it. 
```

2022-09-08 20:10 UTC, dbrian57 commented on specification/resources/serverless/responses/list_namespaces.yml
> +  This will be set to an array of namespace objects, each of which will
```suggestion

```

2022-09-08 20:10 UTC, dbrian57 commented on specification/resources/serverless/responses/list_namespaces.yml
> +  contain the standard attributes associated with a namespace.
```suggestion

```

2022-09-09 03:49 UTC, v-shant commented on specification/resources/serverless/models/create_namespace.yml
> +    example: my namespace
this is freehand text that user can speciify

2022-09-09 03:50 UTC, v-shant commented on specification/resources/serverless/models/namespace_info.yml
> +    description: A unique string format of uuid with a prefix fn-.
No, both are different text

2022-09-09 04:00 UTC, v-shant commented on specification/resources/serverless/sandbox_get.yml
> +  Creates or Gets existing sandbox namespace for the given uuid.
yes

2022-09-09 04:11 UTC, v-shant commented
> I still don't have a clear understanding of the `api-host` field, so that will need to be cleared up to. I tried to be thorough about the line formatting/indentation but it might need another pass after the feedback has been implemented.

api_host basically is a endpoint URL for the APIs

2022-09-09 14:47 UTC, andrewsomething commented on specification/resources/functions/models/not_allowed.yml
> +        example: ['not allowed to get namespace']
Why do 403 errors have a custom format that doesn't match other error responses? Looking at the version history of the RFC, looks like this is a recent addition.

2022-09-09 14:56 UTC, v-shant commented on specification/resources/functions/models/not_allowed.yml
> +        example: ['not allowed to get namespace']
from some RPCs we have to return sone validation errors, like if namespace not present then the error should be Namespace not found (404), similar to this we have a condition where user is not allowed to get response for few namespaces (not restricted to all namespaces). in that case we are returning codes.PermitionDenied and error message= not allowed

on the aggregator side this is being converted to in that format

2022-09-09 15:09 UTC, andrewsomething commented on specification/resources/functions/models/not_allowed.yml
> +        example: ['not allowed to get namespace']
The error code isn't the issue, it is the format of the response body. We document an error format that is used across the API. You 404 error uses it, but not your 403.

```
    {
      "id":       "forbidden",
      "message":  "not allowed to get namespace",
      "request_id": "88d17b7a-630b-4083-99ce-5b91045efdb4"
    }
```

2022-09-09 15:28 UTC, v-shant commented on specification/resources/functions/models/not_allowed.yml
> +        example: ['not allowed to get namespace']
my bad, I don't know from where I got this. just verify in postman and its 

```
{
    "id": "forbidden",
    "message": "not allowed to get namespace",
    "request_id": "b11e45a4-892c-48c9-9001-b6cffe9fe795"
}
```

updating the doc and RFC

2022-09-09 15:39 UTC, andrewsomething commented on specification/resources/functions/models/not_allowed.yml
> +        example: ['not allowed to get namespace']
Thanks!

2022-09-09 16:10 UTC, andrewsomething commented on specification/resources/functions/examples/curl/create_namespace.yml
> +    -d '{"region": "nyc", "label": "my namespace label"}' \
```suggestion
    -d '{"region": "nyc1", "label": "my namespace label"}' \
```

2022-09-09 16:10 UTC, andrewsomething commented on specification/resources/functions/models/create_namespace.yml
> +    example: nyc
```suggestion
    example: nyc1
```

2022-09-09 16:59 UTC, dbrian57 approved these changes
Minor edits, but looks good otherwise 👍

2022-09-09 16:59 UTC, dbrian57 commented on specification/resources/functions/models/namespace_info.yml
> +    description: The api host for the namespace.
```suggestion
    description: |- 
      The namespace's API hostname. Each function in a namespace is provided an endpoint at the namespace's hostname.
```

2022-09-09 17:05 UTC, v-shant commented on specification/resources/functions/models/namespace_info.yml
> +  namespace:
no, in the API response key is namespace

2022-09-14 15:57 UTC, bentranter submitted a review, later dismissed
I'm happy with this now, but let's wait for the other reviewers to re-review before merging

2022-09-14 16:26 UTC, scotchneat requested changes
Overall, the change looks great to me. 

I did bring up a few points and added some suggestions in-line.

2022-09-14 16:26 UTC, scotchneat commented on specification/resources/functions/models/namespace_info.yml
> +properties:
The actual api call includes `created_at` and `updated_at` fields in the response. 
Unless there's a reason we don't want those documented, I think they should be included here.

2022-09-14 16:26 UTC, scotchneat commented on specification/resources/functions/models/create_namespace.yml
> +    description: The [datacenter region](https://docs.digitalocean.com/products/platform/availability-matrix/#available-datacenters) in which to create the namespace.
Since functions aren't available in all regions, we should make sure the linked region reference includes a `Functions Availability` section. Otherwise, the available regions should be listed here.

2022-09-14 16:26 UTC, scotchneat commented on specification/resources/functions/functions_delete_namespace.yml
> +  To delete namespace, send a DELETE request to `/v2/functions/namespaces/{{namespace_id}}`.
The rest of the spec uses the following pattern in docs. It would be good to keep this consistent.

```suggestion
  To delete namespace, send a DELETE request to `/v2/functions/namespaces/$NAMESPACE_ID`.
```

2022-09-14 16:26 UTC, scotchneat commented on specification/resources/functions/functions_get_namespace.yml
> +  To get namespace details, send a GET request to `/v2/functions/namespaces/{{namespace_id}}` with no parameters.
Same as above.

```suggestion
  To get namespace details, send a GET request to `/v2/functions/namespaces/$NAMESPACE_ID` with no parameters.
```

2022-09-14 18:18 UTC, rabbah commented on specification/resources/functions/models/create_namespace.yml
> +    description: The [datacenter region](https://docs.digitalocean.com/products/platform/availability-matrix/#available-datacenters) in which to create the namespace.
@scotchneat are you asking that we link to the available regions only? there is a page in pdocs that says where functions are available that's region based so NYC rather than NYC1 or NYC3.

availability is here https://docs.digitalocean.com/products/functions/details/availability/ although i just noticed this is not up to date.

2022-09-14 18:30 UTC, v-shant commented on specification/resources/functions/models/namespace_info.yml
> +properties:
how about removing them, they are just timestamp stored in the database at the time of adding namespace,

2022-09-15 05:16 UTC, piyush0101 commented on specification/resources/functions/models/create_namespace.yml
> +    description: The [datacenter region](https://docs.digitalocean.com/products/platform/availability-matrix/#available-datacenters) in which to create the namespace.
Functions are available in the following regions - ams3, blr1, fra1, lon1, nyc1, sfo3, sgp1, tor1

2022-09-15 05:16 UTC, piyush0101 submitted a review, later dismissed

2022-09-15 16:43 UTC, scotchneat commented on specification/resources/functions/models/create_namespace.yml
> +    description: The [datacenter region](https://docs.digitalocean.com/products/platform/availability-matrix/#available-datacenters) in which to create the namespace.
> are you asking that we link to the available regions only? 

@rabbah Right. It's a bit misleading as is. Since neither these API docs nor the referenced availability matrix indicate there is limited availability.

2022-09-15 16:49 UTC, scotchneat approved these changes
I think the availability matrix documentation can be handled on the pdocs side at this point so it doesn't have to block this PR. (See my [comment in the review thread](https://github.com/digitalocean/openapi/pull/715#discussion_r972216955)).

Everything else looks good 👍🏽

2022-09-20 13:02 UTC, andrewsomething approved these changes

2022-09-20 13:07 UTC, merged