Functions:Triggers API
digitalocean/openapi pull request #751
Opened 2022-11-11 09:58 UTC by v-shant

2022-11-14 18:12 UTC, scotchneat commented
!deploy

2022-11-14 19:24 UTC, scotchneat commented on specification/resources/functions/models/create_trigger.yml
> +required:
I received an error when testing this endpoint:

```

{
    "id": "bad_request",
    "message": "validating create trigger: validation error: missing source details",
    "request_id": "cc10b7e0-fd80-11ec-b5c1-acde48001122"
}
```

Is `source` another required field missing from this model? Or did I do something wrong with the request?

2022-11-15 05:16 UTC, v-shant commented on specification/resources/functions/models/create_trigger.yml
> +required:
```
{
    "name": "trigger_name4",
    "function": "hello2",
    "is_enabled": false,
    "type": "SCHEDULED",
    "scheduled_details": {
        "cron": "* * * * *"
    }
}
```

this is the required body to create scheduled trigger, can you please share/check if similar is sent

2022-11-15 17:47 UTC, scotchneat reviewed
!deploy

2022-11-15 19:33 UTC, scotchneat requested changes
So far, this is on the right track.

I've left some suggestions inline.

2022-11-15 19:33 UTC, scotchneat commented on specification/resources/functions/functions_get_trigger.yml
> +  Gets the trigger details
```suggestion
  Gets the trigger details.
```

2022-11-15 19:33 UTC, scotchneat commented on specification/resources/functions/functions_get_trigger.yml
> +  To get all triggers, send a GET request to `/v2/functions/namespaces/$NAMESPACE_ID/triggers/$TRIGGER_NAME`.
```suggestion
  To get the trigger details, send a GET request to `/v2/functions/namespaces/$NAMESPACE_ID/triggers/$TRIGGER_NAME`.
```

2022-11-15 19:33 UTC, scotchneat commented on specification/resources/functions/functions_update_trigger.yml
> +  Creates a new trigger for a given function in a namespace. To create a trigger, send a POST request to `/v2/functions/namespaces/$NAMESPACE_ID/triggers/$TRIGGER_NAME` with the `name`, `function`, `
It looks like the models/update_trigger.yml model only expects the `is_enabled` or `scheduled_details` properties.

```suggestion
  Updates the details of the given trigger. To update a trigger, send a PUT request to `/v2/functions/namespaces/$NAMESPACE_ID/triggers/$TRIGGER_NAME` with new values for the `is_enabled ` or `scheduled_details` properties.
```

2022-11-15 19:33 UTC, scotchneat commented on specification/resources/functions/models/trigger_info.yml
> +        example: 2022-11-11T04:16:45Z
It looks like the API can return `null` for this property. This can be described like:

```suggestion
      last_run_at:
        description: Indicates last run time. null value indicates trigger not run yet.
        type: string
        nullable: true
        example: 2022-11-11T04:16:45Z
```

2022-11-15 19:33 UTC, scotchneat commented on specification/resources/functions/models/trigger_info.yml
> +        properties:
The API can also return `null` for this property.

```suggestion
      next_run_at:
        description: Indicates nex run time. null value indicates trigger will not run.
        type: object
        nullable: true
        properties:
```

2022-11-15 19:33 UTC, scotchneat commented on specification/resources/functions/models/trigger_info.yml
> +            example: Welcome to DO!
This object is duplicated across multiple models. I would suggest creating a separate model file for this and referencing it across the other models (see how the [droplet](https://github.com/digitalocean/openapi/blob/main/specification/resources/droplets/models/droplet.yml#L48) model references the `kernel` model).

Also, since the body property is optional, the API appears to return `null` if it was not set. This can be described by adding `nullable: true` to the property details.

2022-11-15 20:36 UTC, danaelhe commented
!deploy

2022-11-15 20:37 UTC, danaelhe reviewed
!deploy

2022-11-15 20:41 UTC, danaelhe reviewed
!deploy

2022-11-16 21:50 UTC, scotchneat approved these changes
Looks great 👍🏽

2022-11-17 15:06 UTC, scotchneat commented
I ran the pydo mocked tests manually using these changes:

```
230 passed, 1 skipped, 98 warnings in 2.06s
```

2022-11-17 15:06 UTC, merged