Separate 'validate client gen' workflow
digitalocean/openapi pull request #756
Opened 2022-11-18 15:35 UTC by scotchneat

This is required for the workflow to have access to the required secrets.

The workflow triggers when the `Spec PR` workflow completes:

```
on:
  workflow_run:
    workflows:
      - 'Spec PR'
    types:
      - completed
```

And only continues if the run was from a `successful` `pull_request` run:

```
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
```

2022-11-18 16:53 UTC, ChiefMateStarbuck approved these changes

2022-11-21 17:35 UTC, andrewsomething requested changes

2022-11-21 17:35 UTC, andrewsomething commented on .github/workflows/validate-client-generation.yml
> +            /repos/scotchneat/openapi/statuses/${{ github.event.workflow_run.head_sha }} \
```suggestion
            /repos/scotchneat/openapi/statuses/${{ github.event.workflow_run.head_sha }} \
```

Does this need to be updated? Looks like a fork.

2022-11-28 15:29 UTC, danaelhe approved these changes

2022-11-28 15:39 UTC, ChiefMateStarbuck approved these changes

2022-12-05 19:08 UTC, andrewsomething approved these changes

2022-12-05 19:19 UTC, merged