DBaS | Add API endpoint for applying cluster patches
digitalocean/openapi pull request #909
Opened 2024-09-08 10:33 UTC by vsharma6855

2024-09-09 17:21 UTC, andrewsomething requested changes
Looks great, but I did have a suggestion in-line re: operationId

2024-09-09 17:21 UTC, andrewsomething commented on specification/resources/databases/databases_update_installUpdate.yml
> +operationId: databases_update_installUpdate
The operation ID is used by client generation tools to produce the method name. For example pydo, our Python client, will end up having a method with the redundant name `databases.update_install_update`. This might be more natural:

```suggestion
operationId: databases_install_update
```

Our linter enforces using consistent operation IDs across our API. As this would be the first PUT using `install`, you'll also need to add it here so that it passes:

https://github.com/digitalocean/openapi/blob/6fddf799ff4318258535091eed0eb7cd50bc6e6c/spectral/functions/validateOpIDNaming.js#L14

2024-09-09 17:55 UTC, danaelhe commented on specification/resources/databases/databases_update_installUpdate.yml
> +  database cluster, send a PUT request to
```suggestion
  To start the installation of updates for a
  database cluster, send a PUT request to
```
I think removing the "now" might be easier to read?

2024-09-17 13:57 UTC, loosla commented on specification/resources/databases/databases_update_installUpdate.yml
> +
I believe a single line in between should be enough.

2024-09-17 14:02 UTC, loosla commented
Looks good to me

2024-09-17 14:35 UTC, andrewsomething commented on specification/resources/databases/databases_update_installUpdate.yml
> +operationId: databases_update_installUpdate
I've pushed an additional commit to allow this to pass the linter check: https://github.com/digitalocean/openapi/pull/909/commits/e41ef07e319a3b74505140c43a88935fcb961c63

2024-09-17 14:36 UTC, andrewsomething approved these changes

2024-09-17 14:37 UTC, merged