VPC Peering Updates
digitalocean/openapi pull request #924
Opened 2024-10-09 19:08 UTC by beardicus

Adds VPC peering info:

- List all peerings: GET `/v2/vpc_peerings`
- Create a new peering: POST  `/v2/vpc_peerings`

- Get a peering: GET `/v2/vpc_peerings/{vpc_peering_id}`
- Update a peering: PATCH `/v2/vpc_peerings/{vpc_peering_id}`
- Delete a peering: DELETE `/v2/vpc_peerings/{vpc_peering_id}`

- List a VPCs peerings: GET `/v2/vpcs/{vpc_id}/peerings`
- Add a peering to a specific VPC: POST `/v2/vpcs/{vpc_id}/peerings`

TODO:

- [ ] I need somebody to check the auth token scopes for each of these
- [ ] A thorough accuracy check from the engineering team would be good
- [ ] A lookover from the API team would be a bonus

2024-10-09 20:20 UTC, andrewsomething commented on specification/resources/vpcs/responses/vpc_peering.yml
> +          status: PROVISIONING
```
/home/asb/projects/openapi/specification/resources/vpcs/vpcs_create_peerings.yml
 40:9  error  oas3-valid-schema-example  "peering" property type must be object  responses[200]
```

This is an annoying subtle issue. The `-` here means the JSON ends up with an array (`{"peering": [ { vpc_peer_details } ]}`) rather than a single object  `{"peering": { vpc_peer_details } }`

```suggestion
        peering:
          id: 6b5c619c-359c-44ca-87e2-47e98170c01d
          name: example-vpc-peering
          vpc_ids:
          - 997615ce-132d-4bae-9270-9ee21b395e5d
          - e51aed59-3bb1-4a6a-8de0-9d1329e9c997
          created_at: '2024-01-09T20:44:32Z'
          status: PROVISIONING
```

2024-10-09 20:45 UTC, andrewsomething requested changes
Great work! I noticed a number of tiny issues and left suggested changes inline,

2024-10-09 20:45 UTC, andrewsomething commented on specification/resources/vpc_peerings/responses/all_vpc_peerings.yml
> +            vpcs:
```suggestion
            vpc_peerings:
```

2024-10-09 20:45 UTC, andrewsomething commented on specification/resources/vpc_peerings/vpc_peerings_get.yml
> +  '202':
```suggestion
  '200':
```

Looks like the GET request returns 200 OK.

2024-10-09 20:45 UTC, andrewsomething commented on specification/resources/vpc_peerings/vpc_peerings_update.yml
> +  '202':
```suggestion
  '200':
```

Same here.

2024-10-09 20:45 UTC, andrewsomething commented on specification/resources/vpcs/vpcs_create_peerings.yml
> +  '200':
```suggestion
  '202':
```

And the create responses return 202s on success.

2024-10-09 20:45 UTC, andrewsomething commented on specification/resources/vpcs/vpcs_list_peerings.yml
> +    - 'vpc:read'
```suggestion
    - 'vpc_peering:read'
```

Let's confirm with the team, but I think this one should be `vpc_peering:read`

2024-10-09 20:45 UTC, andrewsomething commented on specification/resources/vpcs/examples/curl/vpcs_create_peerings.yml
> +    -d '{"name":"example-vpc-peering", "vpc_id": "e51aed59-3bb1-4a6a-8de0-9d1329e9c997"}'
```suggestion
    -d '{"name":"example-vpc-peering", "vpc_id": "e51aed59-3bb1-4a6a-8de0-9d1329e9c997"}' \
```

To make it more copy and paste-able into a terminal.

2024-10-10 15:06 UTC, beardicus commented on specification/resources/vpcs/vpcs_list_peerings.yml
> +    - 'vpc:read'
oops, yep. updated separately before i saw this.

2024-10-10 15:08 UTC, beardicus commented
thanks for the detailed review @andrewsomething ... good catches. this has also been reviewed by the team (slack thread in #vpc-peering-eng) and i've addressed their changes as well.

2024-10-10 15:47 UTC, andrewsomething approved these changes

2024-10-10 17:08 UTC, merged