Added reserved ipv6 API specs
digitalocean/openapi pull request #951
Opened 2024-11-26 14:55 UTC by imaskm

2024-11-26 22:58 UTC, andrewsomething requested changes

2024-11-26 22:58 UTC, andrewsomething commented on specification/resources/reserved_ipv6/reservedIPv6s_create.yml
> +operationId: reservedIPv6s_create
```suggestion
operationId: reservedIPv6_create
```

Unfortunately Autorest, the tool we use to generate the Python client, does not handle this well. It ends up with a signature like `client.reserved_ipv6_s.create()` I've spent some time trying to investigate ways to work around this and have not found a good solution.

I think our best bet here is to just go with `reservedIPv6_create` which becomes `client.reserved_ipv6.create()`. It's a bit inconsistent to not be plural, but I think it is a cleaner approach. 

Thoughts?  (This applies to all of the operation IDs in this PR.)

2024-11-26 22:58 UTC, andrewsomething commented on specification/resources/reserved_ipv6/models/reserved_ipv6_create.yml
> +  region_slug:
Is it not possible to assign an IPv6 address to a Droplet at time of creation like the existing IPv4 functionality?

2024-11-26 22:58 UTC, andrewsomething commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_create.yml
> +                $ref: '../../../shared/models/action_link.yml'
If it can't be assigned to a Droplet at create time, are the `links` ever actually populated?

2024-11-26 22:58 UTC, andrewsomething commented on specification/resources/reserved_ipv6/responses/examples.yml
> +      region_slug: nyc3
```suggestion
  value:
    reserved_ipv6:
      ip: 2409:40d0:f7:1017:74b4:3a96:105e:4c6e
      region_slug: nyc3
```

2024-11-26 22:58 UTC, andrewsomething commented on specification/resources/reserved_ipv6/responses/examples.yml
> +    region_slug: nyc3
```suggestion
  value:
    reserved_ipv6:
      ip: 2409:40d0:f7:1017:74b4:3a96:105e:4c6e
      droplet:
          id: 3164444
          name: example.com
          memory: 1024
          vcpus: 1
          disk: 25
          locked: false
          status: active
          kernel: null
          created_at: '2020-07-21T18:37:44Z'
          features:
          - backups
          - private_networking
          - ipv6
          backup_ids:
          - 53893572
          next_backup_window:
            start: '2020-07-30T00:00:00Z'
            end: '2020-07-30T23:00:00Z'
          snapshot_ids:
          - 67512819
          image:
            id: 63663980
            name: 20.04 (LTS) x64
            type: base
            distribution: Ubuntu
            slug: ubuntu-20-04-x64
            public: true
            regions:
            - ams2
            - ams3
            - blr1
            - fra1
            - lon1
            - nyc1
            - nyc2
            - nyc3
            - sfo1
            - sfo2
            - sfo3
            - sgp1
            - tor1
            created_at: '2020-05-15T05:47:50Z'
            min_disk_size: 20
            size_gigabytes: 2.36
            description: ''
            tags: []
            status: available
            error_message: ''
          volume_ids: []
          size:
            slug: 's-1vcpu-1gb'
            memory: 1024
            vcpus: 1
            disk: 25
            transfer: 1.0
            price_monthly: 5.0
            price_hourly: 0.00743999984115362
            regions:
            - ams2
            - ams3
            - blr1
            - fra1
            - lon1
            - nyc1
            - nyc2
            - nyc3
            - sfo1
            - sfo2
            - sfo3
            - sgp1
            - tor1
            available: true
            description: Basic
          size_slug: s-1vcpu-1gb
          networks:
            v4:
              - ip_address: '10.128.192.124'
                netmask: '255.255.0.0'
                gateway: nil
                type: private
              - ip_address: '192.241.165.154'
                netmask: '255.255.255.0'
                gateway: '192.241.165.1'
                type: public
            v6:
              - ip_address: '2604:a880:0:1010::18a:a001'
                netmask: 64
                gateway: '2604:a880:0:1010::1'
                type: public
          region:
            name: New York 3
            slug: nyc3
            features:
                - backups
                - ipv6
                - metadata
                - install_agent
                - storage
                - image_transfer
            available: true
            sizes:
                - s-1vcpu-1gb
                - s-1vcpu-2gb
                - s-1vcpu-3gb
                - s-2vcpu-2gb
                - s-3vcpu-1gb
                - s-2vcpu-4gb
                - s-4vcpu-8gb
                - s-6vcpu-16gb
                - s-8vcpu-32gb
                - s-12vcpu-48gb
                - s-16vcpu-64gb
                - s-20vcpu-96gb
                - s-24vcpu-128gb
                - s-32vcpu-192g
          tags:
          - web
          - env:prod
          vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
      region_slug: nyc3
```

2024-11-26 22:58 UTC, andrewsomething commented on specification/resources/reserved_ipv6/reservedIPv6s_create.yml
> +summary: Create a New Reserved IPv6
```suggestion
summary: [Beta] Create a New Reserved IPv6
```

My understanding is that these are part of a closed beta. If that's the case, please label them appropriately so that we don't cause confusion for the majority of customers that do not have access.

2024-11-27 00:18 UTC, andrewsomething commented on specification/resources/reserved_ipv6/models/reserved_ipv6.yml
> +    $ref: '../../droplets/models/droplet.yml'
The godo struct also shows a `reserved_at` property that is missing here. Is that part of the API response?

https://github.com/digitalocean/godo/blob/d1b5da305e3b64acc54ca8f98a3e5a65a0ede6d8/reserved_ipv6.go#L34

2024-11-27 05:27 UTC, imaskm commented on specification/resources/reserved_ipv6/reservedIPv6s_create.yml
> +operationId: reservedIPv6s_create
Yes, makes sense, will update

2024-11-27 05:28 UTC, imaskm commented on specification/resources/reserved_ipv6/models/reserved_ipv6_create.yml
> +  region_slug:
No, Reserve and Assign are separate now in IPv6

2024-11-27 05:29 UTC, imaskm commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_create.yml
> +                $ref: '../../../shared/models/action_link.yml'
let me update this, links won't be there

2024-11-27 05:29 UTC, imaskm commented on specification/resources/reserved_ipv6/reservedIPv6s_create.yml
> +summary: Create a New Reserved IPv6
Yes

2024-11-27 05:30 UTC, imaskm commented on specification/resources/reserved_ipv6/models/reserved_ipv6.yml
> +    $ref: '../../droplets/models/droplet.yml'
Yes

2024-11-27 05:32 UTC, imaskm commented on specification/resources/reserved_ipv6/responses/examples.yml
> +      region_slug: nyc3
We don't have `reserved_ipv6` key in API responses for IPv6, as it is just redundant, as we are returning the reserved ipv6, why do we need the key to mention that?

2024-11-27 06:01 UTC, imaskm commented on specification/resources/reserved_ipv6/models/reserved_ipv6.yml
> +    $ref: '../../droplets/models/droplet.yml'
Added

2024-11-27 19:04 UTC, loosla commented on specification/resources/reserved_ipv6/examples/ruby/create_reserved_ipv6.yml
> +lang: Ruby
:wave: Don't think it's a good idea to include Ruby examples while we don't have it in https://github.com/digitalocean/droplet_kit

2024-11-28 08:28 UTC, imaskm commented on specification/resources/reserved_ipv6/examples/ruby/create_reserved_ipv6.yml
> +lang: Ruby
Should I exclude `ruby` directory from this PR then?

2024-11-28 13:43 UTC, loosla commented on specification/resources/reserved_ipv6/examples/ruby/create_reserved_ipv6.yml
> +lang: Ruby
I think that's a good idea to exclude Ruby examples :+1:  Thanks

2024-11-28 18:00 UTC, imaskm commented on specification/resources/reserved_ipv6/examples/ruby/create_reserved_ipv6.yml
> +lang: Ruby
Done, thanks

2024-11-29 15:55 UTC, loosla commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_create.yml
> +          reserved_ipv6:
@andrewsomething Unfortunately, we are encountering the same issue with the API as we did with Logsink. The actual API response differs from what is documented.
Documentation aligns with the DO API. But actual API response not: 
`reserved_ipv6 ` field is missing in a CREATE response.

```console
curl -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
    -d '{"region_slug": "nyc3"}' \
    "https://api.digitalocean.com/v2/reserved_ipv6" 
{"ip":"2604:a880:800:14::4acb:9000","region_slug":"nyc3","reserved_at":"2024-11-29T15:31:30Z"}
```

Same applies to retrieving a single reserved IPv6.

This issue is causing problems during the Terraform implementation, and I was wondering if it would be possible for the team to add  `reserved_ipv6` to the response schema for this API endpoints: CREATE, GET. @imaskm, do you think this is feasible?

Thanks.

2024-11-29 16:22 UTC, imaskm commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_create.yml
> +          reserved_ipv6:
Hey @loosla , this is a mistake from my side, I modified this response 3 days back but I forgot to deploy the changes to master, let me do it

2024-11-29 16:38 UTC, loosla commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_create.yml
> +          reserved_ipv6:
N/A anymore. Ashwani updated the responses. All good now.

2024-12-02 20:32 UTC, loosla commented on specification/resources/reserved_ipv6/examples/curl/delete_reserved_ipv6.yml
> +    "https://api.digitalocean.com/v2/reserved_ips/2409:40d0:f7:1017:74b4:3a96:105e:4c6e"
```suggestion
    "https://api.digitalocean.com/v2/reserved_ipv6/2409:40d0:f7:1017:74b4:3a96:105e:4c6e"
```

2024-12-02 21:13 UTC, loosla commented on specification/resources/reserved_ipv6/models/reserved_ipv6.yml
> +  droplet:
:wave: Could you take a look please? It doesn't seem we return droplet. Same applies to `List`.
```console
curl -X GET     -H "Content-Type: application/json"     -H "Authorization: Bearer $DIGITALOCEAN_TOKEN"     "https://api.digitalocean.com/v2/reserved_ipv6/2604:a880:800:14::4d86:1000"  | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   112  100   112    0     0    288      0 --:--:-- --:--:-- --:--:--   288
{
  "reserved_ipv6": {
    "ip": "2604:a880:800:14::4d86:1000",
    "region_slug": "nyc3",
    "reserved_at": "2024-12-02T21:06:06Z"
  }
}
```

2024-12-03 13:28 UTC, loosla commented on specification/resources/reserved_ipv6/examples/go/list_reserved_ipv6s.yml
> +      reservedIPs, _, err := client.ReservedIPV6.List(ctx, opt)
```suggestion
      reservedIPs, _, err := client.ReservedIPV6s.List(ctx, opt)
```

2024-12-03 13:35 UTC, loosla commented on specification/resources/reserved_ipv6/examples/go/create_reserved_ipv6.yml
> +      }
```suggestion
      }

      reservedIPV6, _, err := client.ReservedIPV6s.Create(ctx, createRequest)
```

2024-12-03 13:37 UTC, loosla commented on specification/resources/reserved_ipv6/examples/go/post_reserved_ipv6_action.yml
> +    // action, _, err := client.ReservedIPV6Actions.Unassign(ctx, "2409:40d0:f7:1017:74b4:3a96:105e:4c6e")
```suggestion
    action, _, err := client.ReservedIPV6Actions.Unassign(ctx, "2409:40d0:f7:1017:74b4:3a96:105e:4c6e")  
```

2024-12-03 14:35 UTC, loosla commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_action.yml
> +          resource_type: reserved_ip
```suggestion
          resource_type: reserved_ipv6
```

2024-12-03 14:37 UTC, loosla commented on specification/resources/reserved_ipv6/examples/curl/post_reserved_ipv6_action.yml
> +  # curl -X POST \
```suggestion
  curl -X POST \
```

2024-12-03 19:20 UTC, loosla commented on specification/resources/reserved_ipv6/examples/python/create_reserved_ipv6.yml
> +  resp = client.reserved_ipv6.create(body=req)
```suggestion
  resp = client.reserved_ipv6s.create(body=req)
```

2024-12-03 19:23 UTC, loosla commented on specification/resources/reserved_ipv6/examples/python/get_reserved_ipv6.yml
> +  resp = client.reserved_ipv6.get(ip="2409:40d0:f7:1017:74b4:3a96:105e:4c6e")
```suggestion
  resp = client.reserved_ipv6s.get(reserved_ipv6="2409:40d0:f7:1017:74b4:3a96:105e:4c6e")
```

2024-12-03 19:24 UTC, loosla commented on specification/resources/reserved_ipv6/examples/python/list_reserved_ipv6s.yml
> +  resp = client.reserved_ipv6.list()
```suggestion
  resp = client.reserved_ipv6s.list()
```

2024-12-03 19:26 UTC, loosla commented on specification/resources/reserved_ipv6/examples/python/post_reserved_ipv6_action.yml
> +  resp = client.reserved_ipv6_actions.post(ip="2409:40d0:f7:1017:74b4:3a96:105e:4c6e", body=req)
```suggestion
  resp = client.reserved_ipv6_actions.post(reserved_ipv6="2409:40d0:f7:1017:74b4:3a96:105e:4c6e", body=req)
```

2024-12-03 19:27 UTC, loosla commented on specification/resources/reserved_ipv6/examples/python/delete_reserved_ipv6.yml
> +  resp = client.reserved_ipv6.delete(ip="2409:40d0:f7:1017:74b4:3a96:105e:4c6e")
```suggestion
  resp = client.reserved_ipv6s.delete(reserved_ipv6="2409:40d0:f7:1017:74b4:3a96:105e:4c6e")
```

2024-12-03 19:29 UTC, loosla commented
:rocket: Many thanks for the updates. Left just a few more suggestions. The rest looks great :+1:

2024-12-04 14:30 UTC, loosla submitted a review, later dismissed
Looks good to me :rocket: 
Thank you for your patience :+1:

2024-12-04 18:27 UTC, imaskm commented
Closing this as there endpoints will be part of a closed beta for now

2025-01-24 08:50 UTC, imaskm commented
@loosla should we replace the [Beta] tagging with "Public Preview" for the public preview release?

2025-01-31 08:30 UTC, imaskm commented
> @imaskm Definitely. That's a good idea 👍 Feel free to remove 'beta'.

@loosla I have replace "Beta" with "Public Preview"

2025-02-11 08:14 UTC, imaskm commented
> > @imaskm Definitely. That's a good idea 👍 Feel free to remove 'beta'.
> 
> @loosla I have replaced "Beta" with "Public Preview"

@loosla  can you please take another look in this PR, it was approved before Beta release.

2025-02-11 15:17 UTC, loosla commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_action.yml
> +                project_id:
:wave: Ashwani, I don't see `project_id` in a curl response. Could you double check please?
If we are not returning it anymore, I think we should remove it in the schema and in examples.

2025-02-11 15:27 UTC, loosla commented on specification/resources/reserved_ipv6/reservedIPv6Actions_post.yml
> +  '401':
It looks like API is returning `request_id` on an error in its response body. I don't think it's necessary as we can get this request_id from headers. For example with `curl -v`.

2025-02-11 15:31 UTC, loosla commented on specification/resources/reserved_ipv6/responses/reserved_ipv6_action.yml
> +          project_id: 746c6152-2fa2-11ed-92d3-27aaa54e4988
Probably should remove `project_id` from examples, if actual API response doesn't contain it.

2025-02-11 15:38 UTC, loosla commented on specification/resources/reserved_ipv6/reservedIPv6_get.yml
> +summary: "[Beta] Retrieve an Existing Reserved IPv6"
Are `Get` and `List` going to be a part of a [Public Preview]?

2025-02-11 15:54 UTC, imaskm commented on specification/resources/reserved_ipv6/reservedIPv6Actions_post.yml
> +  '401':
can you please share the example? I am getting this
```
{"id": "Unauthorized", "message": "Unable to authenticate you" }%   
```

2025-02-11 16:05 UTC, imaskm commented on specification/resources/reserved_ipv6/reservedIPv6Actions_post.yml
> +  '401':
```
{"id":"unprocessable_entity","message":"flipv6 released failed: assigned FLIPv6 cannot be released","request_id":"3dc18450-98b7-421e-96af-88cc03a47437"}

```
we are using this existing response behaviour for reserved IPv4 as well

2025-02-11 16:10 UTC, imaskm commented on specification/resources/reserved_ipv6/reservedIPv6_get.yml
> +summary: "[Beta] Retrieve an Existing Reserved IPv6"
updated

2025-02-11 16:24 UTC, loosla commented on specification/resources/reserved_ipv6/reservedIPv6Actions_post.yml
> +  '401':
```
curl -v -X DELETE   -H "Content-Type: application/json"   -H "Authorization: Bearer $DIGITALOCEAN_TOKEN"   "https://api.digitalocean.com/v2/reserved_ipv6/<my-assigned-ip>"
```

Response:
```
< HTTP/2 422 
{"id":"unprocessable_entity","message":"flipv6 released failed: assigned FLIPv6 cannot be released","request_id":"my-request-id"}
```

If this error is missing in IPv4 and this error is returned by IPv4 API response, we should add it to the IPv4 documentation in a separate PR. This can be something we overlooked earlier.

2025-02-11 17:41 UTC, imaskm commented on specification/resources/reserved_ipv6/reservedIPv6Actions_post.yml
> +  '401':
it's not just this error, see this
```
{"id":"not_found","message":"The resource you requested could not be found.","request_id":"6cfcb9b8-82de-4f50-8b20-358668047668"}


```

2025-02-12 14:50 UTC, loosla commented on specification/resources/reserved_ipv6/models/reserved_ipv6.yml
> +    $ref: '../../droplets/models/droplet.yml'
As droplet is missing when IP is not assigned, let's make it nullable.
```suggestion
    anyOf:
      - title: 'null'
        type: object
        nullable: true
        description: If the reserved IP is not assigned to a Droplet, the
          value will be null.
      - $ref: '../../droplets/models/droplet.yml'

```

2025-02-12 14:51 UTC, loosla commented on specification/resources/reserved_ipv6/models/reserved_ipv6_list.yml
> +          $ref: '../../droplets/models/droplet.yml'
As droplet is missing when IP is not assigned, let's make it nullable.
```suggestion
          anyOf:
            - title: 'null'
              type: object
              nullable: true
              description: If the reserved IP is not assigned to a Droplet, the
                value will be null.
            - $ref: '../../droplets/models/droplet.yml'

```

2025-02-12 14:52 UTC, loosla approved these changes
Left a couple of suggestions. The rest looks good to me. Many thanks :rocket:

2025-02-26 14:03 UTC, loosla approved these changes

2025-02-26 15:34 UTC, andrewsomething approved these changes

2025-02-26 15:36 UTC, merged